# SPDX-FileCopyrightText: : 2017-2022 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

name: pypsa-eur
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - pip

  - atlite>=0.2.6
  - dask

  # Dependencies of the workflow itself
  - xlrd
  - openpyxl
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - yaml
  - pytables
  - lxml
  - powerplantmatching>=0.5.3
  - numpy
  - pandas
  - geopandas>=0.11.0
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely
  - progressbar2
  - matplotlib
  - proj
  - fiona <= 1.18.20  # Till issue https://github.com/Toblerity/Fiona/issues/1085 is not solved
  - country_converter

  # Keep in conda environment when calling ipython
  - ipython

  # GIS dependencies:
  - cartopy
  - descartes
  - rasterio<=1.2.9  # 1.2.10 creates error https://github.com/PyPSA/atlite/issues/238

  # PyPSA-Eur-Sec Dependencies
  - geopy
  - tqdm
  - pytz
  - tabula-py
  - pyxlsb

  # Enable Python kernel for Jupyter notebooks
  - ipykernel
  - jupyterlab
  - jupytext  # a plugin for making raw Jupyter notebooks human-readable and diffable
  - plotly

  # help for visualising Snakemake DAGs
  - graphviz

  - pip:
    - pypsa>=0.20.0
    - vresutils>=0.3.1
    - tsam>=1.1.0
    - tabula-py
    - pyomo
